Implement ESLint
ZoicanDenisUi/Bounce pull request #4
Opened 2021-07-26 09:28 UTC by ZoicanDenisUi

Implementing ESLint for the Bounce project

2021-08-03 08:34 UTC, sergiubologa commented
Please rebase so it can be reviewed.

2021-08-04 09:26 UTC, sergiubologa requested changes

2021-08-04 09:26 UTC, sergiubologa commented on Src/Helpers/domInteractions.ts
> +  // eslint-disable-next-line no-param-reassign
Disabling rules is not ideal. Seems like this rule can be configured to allow this use case. See details here: https://eslint.org/docs/rules/no-param-reassign#props

2021-08-04 09:26 UTC, sergiubologa commented on package.json
> +    "lintAndFix": "npx eslint .\\Src\\**\\*.ts --fix"
why is npx needed here?

2021-08-04 12:12 UTC, ZoicanDenisUi commented on package.json
> +    "lintAndFix": "npx eslint .\\Src\\**\\*.ts --fix"
Deleted npx.

2021-08-04 13:52 UTC, sergiubologa approved these changes

2021-08-04 14:01 UTC, merged